# Generated by Django 3.2.19 on 2023-06-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='contact_message',
            field=models.TextField(max_length=1500),
        ),
    ]
