# Generated by Django 3.2.19 on 2023-06-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactform_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
