# Generated by Django 3.2.19 on 2023-06-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_features_product_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='feature2',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
