# Generated by Django 3.2.19 on 2023-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230612_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='A0_price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='A1_price',
            field=models.DecimalField(decimal_places=2, default=29.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='A2_price',
            field=models.DecimalField(decimal_places=2, default=24.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='A3_price',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='A4_price',
            field=models.DecimalField(decimal_places=2, default=14.99, max_digits=6),
        ),
    ]
