# Generated by Django 3.2.19 on 2023-06-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature3',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
