# Generated by Django 3.2.19 on 2023-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_feature3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image2_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
