# Generated by Django 3.2.19 on 2023-06-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230624_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='A0_price',
            new_name='a0_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='A1_price',
            new_name='a1_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='A2_price',
            new_name='a2_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='A3_price',
            new_name='a3_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='A4_price',
            new_name='a4_price',
        ),
    ]
