# Generated by Django 3.2.19 on 2023-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_size',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
